### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by aruneko** [mycityreport/mcr-api-server#3]
# ToDo
- [x] add Dockerfile
- [x] add docker-compose.yml
- [x] build and push an docker image on Github Actions
- [x] enable build cache
